markdown:    redcarpet
highlighter: pygments

permalink: /posts/:year/:month/:title
relative_permalinks: true

title: Ace
url: http://aliou.github.io/ace
# baseurl: /
description: Ace, a Jekyll theme.

paginate: 5
paginate_path: '/:num'

exclude: [Gemfile, Gemfile.lock, gulpfile.js, package.json, node_modules, css]

footer:
  - description: true
  - social:
    - twitter: aliouftw
    - github: aliou
    - rss: true
